### ISSUE TITLE
Deterministic serialization of chat demo app state

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/mir#13]
When taking a snapshot of the application state, the serialization must be performed deterministically,
such that all nodes can agree on a snapshot. Currently, a protobuf message is used to serialize the chat demo app state.
The protocol buffer implementation, however, does not guarantee deterministic serialization.

While in practice (in the concrete case of the chat demo app) the state snapshot is always the same, technically this is not guaranteed.

Fix this by providing a deterministic implementation of the `Snapshot()` method of the chat demo app logic:
https://github.com/filecoin-project/mir/blob/946689a112983e6384d6c697c01de00d0f433d14/samples/chat-demo/app.go#L75

**Comment by ranchalp** [comment]
This has already been solved in the main branch.
