### ISSUE TITLE
Consider using MADR template for decision records

### ISSUE THREAD

**Issue by sergefdrv** [filecoin-project/mir#16]
I like [MADR](https://adr.github.io/madr/) template more because it clearly calls for considering alternative options and summarize the decision outcome concisely as an [Y-statement](https://medium.com/@docsoc/y-statements-10eb07b5a177).

_Originally posted by @sergefdrv in https://github.com/filecoin-project/mir/pull/14#discussion_r854943395_

**Comment by matejpavlovic** [comment]
That's fine with me, I don't mind using that template for future ADRs.

**Comment by sergefdrv** [comment]
@dnkolegov what is your preference?

**Comment by dnkolegov** [comment]
I am ok with MADR
