### ISSUE TITLE
Chat demo prints a bunch of warnings to the console

### ISSUE THREAD

**Issue by xosmig** [filecoin-project/mir#187]
The app prints a bunch of network-related warnings (about connections being refused) in non-verbose mode even when everything works as intended.
I believe, warnings should only be printed when something unexpected happens.

@dnkolegov could you take a look? We probably need to modify the networking module so that it only prints warnings if it cannot establish the connection after some timeout or some unexpected error happens (i.e., anything other than "connection refused" I guess).

**Comment by xosmig** [comment]
@matejpavlovic chat-demo also outputs "New epoch: XX" every few seconds. Is it supposed to happen in non-verbose mode?

**Comment by dnkolegov** [comment]
> We probably need to modify the networking module so that it only prints warnings if it cannot establish the connection after some timeout or some unexpected error happens (i.e., anything other than "connection refused" I guess).

Why is that? Why do you think that:

-  if we cannot connect to a node the first time it is not an error but if we cannot connect to the same node 3 times then it becomes an error?
- if we cannot connect to the node then it is not unexpected?

We see this behavior in the demo because 4 nodes start "simultaneously", so that's the demo problem but not the libp2p transport problem.

**Comment by matejpavlovic** [comment]
Yes the new epoch notifications should go away. I'll take care of that.

As for the networking, the question is whether a failed connection attempt is worth a warning (I'd say it probably is). I think that the networking layer is actually ok. To get rid of the initial warnings, we could have the first failed connection attempt only print an info-level entry and have a warning only if an actual timeout is involved. It's easy to fix and I'll do that at some point when my brain is too tired for more writing more involved code.

**Comment by dnkolegov** [comment]
I don't understand why we are worrying about this, especially for the samples apps. But I added Matej's suggestion - https://github.com/filecoin-project/mir/pull/190

@xosmig and @matejpavlovic please review.

**Comment by xosmig** [comment]
> Why do you think that if we cannot connect to a node the first time it is not an error 

Because we cannot expect all nodes to start simultaneously. So, it is expected that they won't be able to connect to each other immediately after start. 

> Why do you think that if we cannot connect to the same node 3 times then it becomes an error

It is slightly more reasonable to expect the nodes to start within, say, a few seconds from each other, than exactly at the same instant. However, I wouldn't call it an error even if they cannot connect for a significant amount of time. I would probably rather make it a warning and would continue the attempts to reconnect into infinity.

However, this touches on a more complicated topic of the `net` module interface (see: #132).

> I don't understand why we are worrying about this

Because an app is not supposed to output warnings unless something is not right, so, technically, I'd say that it is a bug.
However, you're right that it's clearly not a very important one, I just created an issue to keep track of it.

> especially for the samples apps

I think it won't be different for non-sample apps.
Also, sample apps are also supposed to work without any errors/warnings I think.
