### ISSUE TITLE
ISS runtime error

### ISSUE THREAD

**Issue by dnkolegov** [filecoin-project/mir#203]
Found this while I was searching for a data race in Eudico:

panic: miner consensus error: could not process PassiveModule (iss) events: module panicked: runtime error: index out of range [2] with length 2
Stack trace:
goroutine 11126 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/runtime/debug/stack.go:24 +0x70
github.com/filecoin-project/mir.safelyApplyEventsPassive.func1()
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/workers.go:130 +0x68
panic({0x1088d5f40, 0xc004be78f0})
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/runtime/panic.go:844 +0x258
github.com/filecoin-project/mir/pkg/iss.(*ISS).applySBMessage(0xc004e44aa0, 0xc004405c80, {0xc00525de40, 0x36})
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/pkg/iss/iss.go:874 +0xb2c
github.com/filecoin-project/mir/pkg/iss.(*ISS).applyMessageReceived(0xc004e44aa0?, 0xc004405d40)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/pkg/iss/iss.go:698 +0x16c
github.com/filecoin-project/mir/pkg/iss.(*ISS).ApplyEvent(0xc004fb5268?, 0xc00404f8c0)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/pkg/iss/iss.go:334 +0x6ac
github.com/filecoin-project/mir/pkg/modules.ApplyEventsSequentially(0xc004fb5250, 0xc001693c18)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/pkg/modules/eventprocessing.go:24 +0x1f0
github.com/filecoin-project/mir/pkg/iss.(*ISS).ApplyEvents(0xc004e44aa0, 0xc004fb5260?)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/pkg/iss/iss.go:288 +0x50
github.com/filecoin-project/mir.safelyApplyEventsPassive({0x115d730d8, 0xc004e44aa0}, 0xc004e44aa0?)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/workers.go:137 +0x7c
github.com/filecoin-project/mir.(*Node).processModuleEvents(0xc003932e00, {0x108a90318, 0xc000936f00}, {0x108a73340?, 0xc004e44aa0}, 0xc003d4ca20, 0xc003d4c960)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/workers.go:83 +0x174
github.com/filecoin-project/mir.(*Node).startModules.func1({0x103a747d6, 0x3}, {0x108a73340, 0xc004e44aa0}, 0x0?)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/node.go:327 +0x11c
created by github.com/filecoin-project/mir.(*Node).startModules
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220824090136-077a93b8d116/node.go:315 +0x32c

**Comment by matejpavlovic** [comment]
Nice catch, I found the bug that is the primary cause of this issue and fixed in #204 .
In essence, the node received a message that it should have ignored.

That said, I'm wondering why the node received such a message (assuming no failures were simulated in the run) in the first place...
Can you reproduce the issue? What exactly were you doing when it occurred? Adding a node? Removing a node?

**Comment by dnkolegov** [comment]
I will try to reproduce it.

> What exactly were you doing when it occurred?

That's adding a node flow but I added `time.Sleep(time.Duration(rand.Intn(1000)) * time.Millisecond)` in several places in Eudico's subnet manager: into `getSubnet()` and `getParentAPI()`.

**Comment by matejpavlovic** [comment]
Thanks. Just make sure to use the old version of the code, as I already merged the fix, which would make the problem look very different even if it occurs.

**Comment by matejpavlovic** [comment]
This seems resolved.
