### ISSUE TITLE
Use make for building

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/mir#23]
Standardize Makefile targets for
- testing
- linting
- building
- cleaning
- generating code

**Comment by sergefdrv** [comment]
[MinBFT's Makefile](https://github.com/hyperledger-labs/minbft/blob/main/Makefile) can serve as an example.

**Comment by dnkolegov** [comment]
And this one from Eudico - https://github.com/filecoin-project/eudico/blob/eudico/Makefile
