### ISSUE TITLE
Re-establish lost network connections

### ISSUE THREAD

**Issue by jsoares** [filecoin-project/mir#237]
Candidates: @dnkolegov @adlrocha 
Estimate: 1wk

> In the Net module, when the underlying transport’s connection breaks, the module transparently re-establishes it, dropping the corresponding outgoing messages in the meantime.
> If necessary for stability, add small buffers for outgoing messages while the corresponding connection is being (re-)established.
> Implement with libp2p transport only

**Comment by dnkolegov** [comment]
This mechanism is implemented as a part of Mir network transport improvement in https://github.com/filecoin-project/mir/pull/230.
