### ISSUE TITLE
Update and generalize mircat and the debugger

### ISSUE THREAD

**Issue by jsoares** [filecoin-project/mir#243]
Candidates: @matejpavlovic 
Estimate: 1wk

**Comment by jsoares** [comment]
![image](https://user-images.githubusercontent.com/547492/199561193-dd0c9dcc-0fe9-48a6-9e39-498345653f3e.png)

@matejpavlovic does this mean we're also descoping mircat from the M1.2 deliverable? And is "later" defined?

**Comment by matejpavlovic** [comment]
@ranchalp contributed a small update ( #295 ) that already proved pretty useful. While there is plenty of other things that can be improved further down this path, I think we're good for the initial Spacenet launch with mircat.
