### ISSUE TITLE
Add batch timeout capability to mempool

### ISSUE THREAD

**Issue by jsoares** [filecoin-project/mir#249]
Candidates: @dnkolegov 
Estimate: 1wk

**Comment by matejpavlovic** [comment]
I removed the P0 tag, as this is actually not really critical and purely performance-related. I had initially put it among the P0 tasks, as it was a natural (small) part of implementing the mempool that we needed to work on anyway. The system can, however, work fine without it, just not with optimal performance. The change can be implemented later when there is less time pressure.

**Comment by matejpavlovic** [comment]
Oh, this is outdated, actually, sorry, I forgot to close it. In the end we don't have a batch timeout directly in the mempool, but we achieved the same effect by other means.
