### ISSUE TITLE
Null module

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/mir#296]
- Introduce a "null" module (with module ID `"null"`) present by default. The null module will simply ignore all incoming events.
- Create a constant (in the types package) for the ID of the null module.

**Comment by ranchalp** [comment]
This was already done by @matejpavlovic I believe. Feel free to close upon confirmation.

**Comment by ranchalp** [comment]
Done, and from #320 there is support to use the null module in order to split logging into multiple files.
