### ISSUE TITLE
Mempool and fakebatchdb converting from []bytes to string protobufs error

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/mir#340]
At the moment, `txID`  and`BatchID` ( byte arrays that do not necessarily follow a [UTF-8 String convention](https://en.wikipedia.org/wiki/UTF-8)) are [casted to string](https://github.com/filecoin-project/mir/blob/e7dc27160d7d9be70e16d6c046c4f6e0ecba284c/pkg/types/types.go#L110). This can lead to an error [by protobufs](https://github.com/protocolbuffers/protobuf/issues/4970) when treating a []byte as a string by protobuffers (as the autogenerated DSL's code does), when converting from []byte to string, if the underlying byte array does not have a UTF-8 string representation.

A solution is to simply change the `txID` type to `[]byte`, but `[]byte` cannot be used as a key for [maps](https://github.com/filecoin-project/mir/blob/e7dc27160d7d9be70e16d6c046c4f6e0ecba284c/pkg/mempool/simplemempool/simplemempool.go#L46). A quick workaround is to define these two types as repeated bytes and cast to string once they are retrieved in []byte variables in go.

**Comment by matejpavlovic** [comment]
This is subsumed by #356
