### ISSUE TITLE
Tagging `bytes` protobuffers with mir type results in wrong conversion

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/mir#356]
Protobuffers `bytes` are converted to slices `[]uint8` in Go. Because of this, when tagging a `bytes` type with a go type using `mir.type`  (for example, `type TxID []byte`) in protobuffers, the codegen actually takes the tagged type and uses it to replace the underlying type of the slice, i.e. `uint8`. As a result, the resulting type is `[]TxID` instead of `TxID`. A similar behavior is expected when tagging map types with `mir.key_type` and `mir.value_type`.

The proposal consists of creating a new tag, `mir.outer_type`, that if defined tells the codegen to actually convert the entire the entire slice or map, instead of the underlying types.

**Comment by xosmig** [comment]
I imagine, with the suggested fix (a new annotation), there could be an issue with `repeated bytes` fields.

**Comment by xosmig** [comment]
Although, the feature of wrapping the repeated field, as well as maps, would be nice on its own :)
(either with a new annotation or with `(mir.type)` as suggested in https://github.com/filecoin-project/mir/pull/348#discussion_r1121774305)
