### ISSUE TITLE
Investigate how to propagate data from Mir to Eudico to be able to derive block miners

### ISSUE THREAD

**Issue by dnkolegov** [filecoin-project/mir#43]
To send a Filecoin block in Eudico we need the miner who has mined this block.
At present, Mir doesn't provide control-plane information regarding proposed blocks.
In integrating Tendermint into Eudico, we used the following approach: Filecoin block miner is a Eudico node which corresponding Tendermin node proposed this block.

**Comment by matejpavlovic** [comment]
Subsumed by more general #308 .
