### ISSUE TITLE
Checkpoint typo did not trigger FAILed tests, why?

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/mir#468]
@matejpavlovic  and I have recently found [this bug](https://github.com/filecoin-project/mir/blob/55a940a4ab7c5d0bdd97d908748556b8776c8cd8/pkg/checkpoint/checkpoint.go#L221) in which we missed the `!` before the `reflect.DeepEqual`. While this is an easy-to-solve typo (coming in a PR soon), it is not expected that all tests PASSed given this error when verifying the checkpoint. 

We need to know why is that. We came up with the possibility that this is because the introduction of the async multisig collector means that in the first epoch all the transactions in all tests are delivered, so no checkpoint actually need to be verified in the tests. It could be this or something else, but we need to figure it out and resolve it so that the tests are comprehensive again.

**Comment by ranchalp** [comment]
Typo resolved in [this PR,](https://github.com/filecoin-project/mir/pull/469) but issue remains that we need to understand and fix at least testing.

**Comment by matejpavlovic** [comment]
In addition to figuring out why the tests passed despite the error, we should write unit tests for the checkpoint, which should have discovered that bug in the first place.

**Comment by matejpavlovic** [comment]
Good news. It is what I suspected - the async multisig collector. The system is just too fast to notice the problem with the checkpoint, because everything gets delivered before the checkpoint. When I set the limit of sub-certificates in the multisig collector back to one, the test fails as it should.
