### ISSUE TITLE
Test strategy for Mir

### ISSUE THREAD

**Issue by sergefdrv** [filecoin-project/mir#72]
Prepare a test strategy for Mir framework. The test strategy should outline the testing objectives and approach to ensure decent stability of the Mir framework and ISS implementation within such that it can be eventually used as a reliable consensus mechanism in sub-chains of Filecoin with hierarchical consensus.

The document: https://hackmd.io/EAak8WMCQBaHAN8i94IyBw.

**Comment by dnkolegov** [comment]
There is a document we have already started - https://hackmd.io/OEIctHWCQV6tmJwVUGNX0Q

**Comment by sergefdrv** [comment]
> There is a document we have already started - https://hackmd.io/OEIctHWCQV6tmJwVUGNX0Q

This document seems to focus, for the most part, on Eudico and its integration with Mir. In the scope of this issue, I would like to focus on testing Mir and ISS.

**Comment by sergefdrv** [comment]
I created a new document to describe test strategy specifically for Mir/ISS in more detail: https://hackmd.io/EAak8WMCQBaHAN8i94IyBw.
