### ISSUE TITLE
Transport (Net module) based on libp2p

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/mir#81]
Implement the `Net` module's interface using the libp2p-based transport layer used in Eudico.

Estimated duration: 2 weeks

**Comment by matejpavlovic** [comment]
## 2022-07-05 Sync meeting summary

### Situation

The Eudico daemon and the Eudico miner run in 2 different processes. Both of them are necessary to run consensus and produce blocks. The Mir implementation runs in the miner process (as this is more natural given the Eudico architecture) and communicates with the daemon to fetch transactions from the mempool and deliver ordered blocks to it.

The libp2p host that Eudico uses (and that could potentially be reused by Mir) only runs in the daemon and is not available to the miner. However, moving the whole Mir-based ordering implementation to the daemon seems to be hard without perturbing the Eudico implementation.

### Conclusion

Have an independent instance of a libp2p host inside the miner process, independent of the Eudico daemon and only used for transporting the consensus protocol messages. It will be encapsulated in a Mir networking module for interaction with Mir. If we ever decide to move the Mir-based ordering component inside the Eudico daemon process, we will modify the Mir module and make it use the Eudico-native libp2p host instead.

**Comment by dnkolegov** [comment]
Implemented in https://github.com/filecoin-project/mir/pull/126
